# Generated by Django 4.2.13 on 2024-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('dept', models.CharField(max_length=100, null=True)),
                ('CGPA', models.FloatField(default=0, max_length=10)),
            ],
        ),
    ]
