# Generated by Django 4.2.13 on 2024-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feedback',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
