# Generated by Django 4.2.13 on 2024-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
