# Generated by Django 4.2.13 on 2024-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
    ]
