# Generated by Django 4.2.13 on 2024-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
