# Generated by Django 4.2.13 on 2024-07-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CGPA',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
    ]
