# Generated by Django 4.2.13 on 2024-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CGPA',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='product',
            name='passed',
        ),
        migrations.AddField(
            model_name='product',
            name='Event_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tot_members',
            field=models.IntegerField(null=True),
        ),
    ]
