# Generated by Django 4.2.13 on 2024-08-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tot_members',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
